import type {
  Driver,
  Customer,
  Route,
  Stop,
  Review,
  Message,
  Notification,
  Alert,
  ChatThread,
  PerformanceMetrics,
} from './types';

// San Francisco area coordinates for demo
const SF_CENTER = { lat: 37.7749, lng: -122.4194 };

export const mockDrivers: Driver[] = [
  {
    id: 'driver-1',
    name: 'Marcus Johnson',
    email: 'marcus.j@poobel.com',
    phone: '+1 (415) 555-0101',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    vehicleId: 'VH-001',
    vehiclePlate: 'POO-1234',
    status: 'en_route',
    currentLocation: { lat: 37.7849, lng: -122.4094 },
    rating: 4.8,
    totalRatings: 156,
    completedStops: 847,
    totalStops: 892,
    onTimeRate: 94.5,
    earlyCount: 234,
    lateCount: 45,
    missedCount: 12,
  },
  {
    id: 'driver-2',
    name: 'Sarah Chen',
    email: 'sarah.c@poobel.com',
    phone: '+1 (415) 555-0102',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    vehicleId: 'VH-002',
    vehiclePlate: 'POO-5678',
    status: 'at_stop',
    currentLocation: { lat: 37.7649, lng: -122.4294 },
    rating: 4.9,
    totalRatings: 203,
    completedStops: 1024,
    totalStops: 1056,
    onTimeRate: 97.2,
    earlyCount: 312,
    lateCount: 32,
    missedCount: 8,
  },
  {
    id: 'driver-3',
    name: 'James Wilson',
    email: 'james.w@poobel.com',
    phone: '+1 (415) 555-0103',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    vehicleId: 'VH-003',
    vehiclePlate: 'POO-9012',
    status: 'available',
    currentLocation: { lat: 37.7549, lng: -122.4394 },
    rating: 4.6,
    totalRatings: 89,
    completedStops: 512,
    totalStops: 548,
    onTimeRate: 91.8,
    earlyCount: 145,
    lateCount: 67,
    missedCount: 21,
  },
  {
    id: 'driver-4',
    name: 'Elena Rodriguez',
    email: 'elena.r@poobel.com',
    phone: '+1 (415) 555-0104',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
    vehicleId: 'VH-004',
    vehiclePlate: 'POO-3456',
    status: 'completed',
    currentLocation: { lat: 37.7749, lng: -122.4494 },
    rating: 4.7,
    totalRatings: 134,
    completedStops: 678,
    totalStops: 712,
    onTimeRate: 95.1,
    earlyCount: 198,
    lateCount: 34,
    missedCount: 15,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'customer-1',
    name: 'Alex Thompson',
    email: 'alex.t@email.com',
    phone: '+1 (415) 555-1001',
    address: '123 Market Street, San Francisco, CA 94102',
    coordinates: { lat: 37.7879, lng: -122.4074 },
    serviceType: 'residential',
    binLocation: 'Left side of driveway',
    scheduleDays: ['Monday', 'Thursday'],
    nextPickupDate: '2024-12-18',
    assignedDriverId: 'driver-1',
  },
  {
    id: 'customer-2',
    name: 'Jordan Lee',
    email: 'jordan.l@email.com',
    phone: '+1 (415) 555-1002',
    address: '456 Valencia Street, San Francisco, CA 94103',
    coordinates: { lat: 37.7649, lng: -122.4219 },
    serviceType: 'residential',
    binLocation: 'Behind the gate, code required',
    accessCode: '4521',
    scheduleDays: ['Tuesday', 'Friday'],
    nextPickupDate: '2024-12-17',
    assignedDriverId: 'driver-1',
  },
  {
    id: 'customer-3',
    name: 'Morgan Garcia',
    email: 'morgan.g@email.com',
    phone: '+1 (415) 555-1003',
    address: '789 Divisadero Street, San Francisco, CA 94117',
    coordinates: { lat: 37.7749, lng: -122.4384 },
    serviceType: 'recycling',
    binLocation: 'Alley entrance',
    scheduleDays: ['Wednesday'],
    nextPickupDate: '2024-12-18',
    assignedDriverId: 'driver-2',
  },
  {
    id: 'customer-4',
    name: 'Casey Martinez',
    email: 'casey.m@email.com',
    phone: '+1 (415) 555-1004',
    address: '321 Haight Street, San Francisco, CA 94117',
    coordinates: { lat: 37.7699, lng: -122.4469 },
    serviceType: 'residential',
    binLocation: 'Front porch',
    notes: 'Ring doorbell after pickup',
    scheduleDays: ['Monday', 'Thursday'],
    nextPickupDate: '2024-12-19',
    assignedDriverId: 'driver-2',
  },
  {
    id: 'customer-5',
    name: 'Taylor Wong',
    email: 'taylor.w@email.com',
    phone: '+1 (415) 555-1005',
    address: '555 Castro Street, San Francisco, CA 94114',
    coordinates: { lat: 37.7609, lng: -122.4350 },
    serviceType: 'commercial',
    binLocation: 'Loading dock, rear entrance',
    accessCode: '7890',
    scheduleDays: ['Monday', 'Wednesday', 'Friday'],
    nextPickupDate: '2024-12-18',
    assignedDriverId: 'driver-3',
  },
];

const today = new Date().toISOString().split('T')[0];

export const mockStops: Stop[] = [
  {
    id: 'stop-1',
    routeId: 'route-1',
    customerId: 'customer-1',
    address: '123 Market Street, San Francisco, CA 94102',
    coordinates: { lat: 37.7879, lng: -122.4074 },
    scheduledTime: '08:00',
    actualTime: '07:55',
    status: 'completed',
    serviceType: 'residential',
    binLocation: 'Left side of driveway',
    sequence: 1,
  },
  {
    id: 'stop-2',
    routeId: 'route-1',
    customerId: 'customer-2',
    address: '456 Valencia Street, San Francisco, CA 94103',
    coordinates: { lat: 37.7649, lng: -122.4219 },
    scheduledTime: '08:30',
    status: 'in_progress',
    serviceType: 'residential',
    binLocation: 'Behind the gate, code required',
    accessCode: '4521',
    sequence: 2,
  },
  {
    id: 'stop-3',
    routeId: 'route-1',
    customerId: 'customer-3',
    address: '789 Divisadero Street, San Francisco, CA 94117',
    coordinates: { lat: 37.7749, lng: -122.4384 },
    scheduledTime: '09:00',
    status: 'pending',
    serviceType: 'recycling',
    binLocation: 'Alley entrance',
    sequence: 3,
  },
  {
    id: 'stop-4',
    routeId: 'route-1',
    customerId: 'customer-4',
    address: '321 Haight Street, San Francisco, CA 94117',
    coordinates: { lat: 37.7699, lng: -122.4469 },
    scheduledTime: '09:30',
    status: 'pending',
    serviceType: 'residential',
    binLocation: 'Front porch',
    notes: 'Ring doorbell after pickup',
    sequence: 4,
  },
  {
    id: 'stop-5',
    routeId: 'route-1',
    customerId: 'customer-5',
    address: '555 Castro Street, San Francisco, CA 94114',
    coordinates: { lat: 37.7609, lng: -122.4350 },
    scheduledTime: '10:00',
    status: 'pending',
    serviceType: 'commercial',
    binLocation: 'Loading dock, rear entrance',
    accessCode: '7890',
    sequence: 5,
  },
  {
    id: 'stop-6',
    routeId: 'route-2',
    customerId: 'customer-1',
    address: '123 Market Street, San Francisco, CA 94102',
    coordinates: { lat: 37.7879, lng: -122.4074 },
    scheduledTime: '14:00',
    status: 'pending',
    serviceType: 'residential',
    binLocation: 'Left side of driveway',
    sequence: 1,
  },
];

export const mockRoutes: Route[] = [
  {
    id: 'route-1',
    name: 'Downtown Morning Route',
    driverId: 'driver-1',
    date: today,
    startTime: '07:30',
    status: 'in_progress',
    stops: mockStops.filter(s => s.routeId === 'route-1'),
    totalDistance: 12.5,
    estimatedDuration: 180,
  },
  {
    id: 'route-2',
    name: 'Mission District Afternoon',
    driverId: 'driver-2',
    date: today,
    startTime: '13:00',
    status: 'scheduled',
    stops: mockStops.filter(s => s.routeId === 'route-2'),
    totalDistance: 8.3,
    estimatedDuration: 120,
  },
  {
    id: 'route-3',
    name: 'Sunset Route',
    driverId: 'driver-3',
    date: today,
    startTime: '06:00',
    endTime: '11:30',
    status: 'completed',
    stops: [],
    totalDistance: 15.2,
    estimatedDuration: 240,
  },
];

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    customerId: 'customer-1',
    driverId: 'driver-1',
    stopId: 'stop-1',
    rating: 5,
    comment: 'Marcus was very professional and on time!',
    createdAt: '2024-12-16T08:30:00Z',
  },
  {
    id: 'review-2',
    customerId: 'customer-3',
    driverId: 'driver-2',
    stopId: 'stop-3',
    rating: 5,
    comment: 'Excellent service as always',
    createdAt: '2024-12-15T10:15:00Z',
  },
  {
    id: 'review-3',
    customerId: 'customer-2',
    driverId: 'driver-1',
    stopId: 'stop-2',
    rating: 4,
    comment: 'Good job, just a bit early',
    createdAt: '2024-12-14T09:45:00Z',
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    senderId: 'dispatch',
    senderType: 'dispatch',
    receiverId: 'driver-1',
    receiverType: 'driver',
    content: 'New stop added to your route at 555 Castro Street',
    timestamp: '2024-12-17T08:15:00Z',
    read: true,
  },
  {
    id: 'msg-2',
    senderId: 'driver-1',
    senderType: 'driver',
    receiverId: 'dispatch',
    receiverType: 'dispatch',
    content: 'Acknowledged, heading there now',
    timestamp: '2024-12-17T08:16:00Z',
    read: true,
  },
  {
    id: 'msg-3',
    senderId: 'customer-2',
    senderType: 'customer',
    receiverId: 'driver-1',
    receiverType: 'driver',
    content: 'Please ring the bell when you arrive',
    timestamp: '2024-12-17T08:20:00Z',
    read: false,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'customer-1',
    type: 'completed',
    title: 'Pickup Completed',
    message: 'Your waste pickup has been completed by Marcus',
    timestamp: '2024-12-17T08:00:00Z',
    read: false,
  },
  {
    id: 'notif-2',
    userId: 'customer-2',
    type: 'approaching',
    title: 'Driver Approaching',
    message: 'Your driver Marcus will arrive in approximately 15 minutes',
    timestamp: '2024-12-17T08:15:00Z',
    read: false,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'alert-1',
    type: 'delay',
    severity: 'medium',
    title: 'Route Delay',
    message: 'Driver Marcus is running 10 minutes behind schedule due to traffic',
    driverId: 'driver-1',
    routeId: 'route-1',
    timestamp: '2024-12-17T08:45:00Z',
    resolved: false,
  },
  {
    id: 'alert-2',
    type: 'incident',
    severity: 'low',
    title: 'Bin Access Issue',
    message: 'Unable to access bin at 789 Oak Street - gate locked',
    driverId: 'driver-2',
    routeId: 'route-2',
    timestamp: '2024-12-17T09:30:00Z',
    resolved: true,
  },
];

export const mockChatThreads: ChatThread[] = [
  {
    id: 'chat-1',
    customerId: 'customer-1',
    title: 'Schedule Question',
    messages: [
      {
        id: 'chat-msg-1',
        role: 'user',
        content: 'When is my next pickup scheduled?',
        timestamp: '2024-12-16T10:00:00Z',
      },
      {
        id: 'chat-msg-2',
        role: 'assistant',
        content: 'Your next pickup is scheduled for December 18th, 2024. Marcus Johnson will be your driver, and you can expect them around 8:00 AM based on the route schedule.',
        timestamp: '2024-12-16T10:00:05Z',
      },
    ],
    createdAt: '2024-12-16T10:00:00Z',
    updatedAt: '2024-12-16T10:00:05Z',
  },
];

export const mockPerformanceMetrics: PerformanceMetrics[] = [
  { date: '2024-12-11', completedStops: 42, totalStops: 45, onTimeRate: 93.3, avgCompletionTime: 4.2, distance: 28.5 },
  { date: '2024-12-12', completedStops: 48, totalStops: 48, onTimeRate: 100, avgCompletionTime: 3.8, distance: 31.2 },
  { date: '2024-12-13', completedStops: 45, totalStops: 47, onTimeRate: 95.7, avgCompletionTime: 4.1, distance: 29.8 },
  { date: '2024-12-14', completedStops: 50, totalStops: 52, onTimeRate: 96.2, avgCompletionTime: 3.9, distance: 33.1 },
  { date: '2024-12-15', completedStops: 38, totalStops: 40, onTimeRate: 95.0, avgCompletionTime: 4.0, distance: 25.6 },
  { date: '2024-12-16', completedStops: 44, totalStops: 46, onTimeRate: 95.7, avgCompletionTime: 4.3, distance: 30.2 },
  { date: '2024-12-17', completedStops: 23, totalStops: 48, onTimeRate: 91.3, avgCompletionTime: 4.5, distance: 15.8 },
];

// Helper function to get a random location near SF
export function getRandomSFLocation(): { lat: number; lng: number } {
  return {
    lat: SF_CENTER.lat + (Math.random() - 0.5) * 0.05,
    lng: SF_CENTER.lng + (Math.random() - 0.5) * 0.05,
  };
}

// Generate random ID
export function generateId(): string {
  return Math.random().toString(36).substring(2, 9);
}

